# Generated by Django 5.0.7 on 2024-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='operation_airlines',
            field=models.CharField(choices=[('Air France', 'Air France'), ('KLM', 'KLM'), ('Lufthansa', 'Lufthansa'), ('British Airways', 'British Airways'), ('Emirates', 'Emirates')], max_length=100),
        ),
    ]
